// -------------------------------------------------------------
// 
// File Name: C:\Users\gyana\OneDrive\Pictures\Documents\MATLAB\VLSI_FPGA_CoDesign_MATLAB_to_HDL\matlab\codegen\fir_filter_hdl\hdlsrc\fir_filter_hdl_fixpt.v
// Created: 2026-10-03 20:08:23
// 
// Generated by MATLAB 24.2, MATLAB Coder 24.2 and HDL Coder 24.2
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// y                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fir_filter_hdl_fixpt
// Source Path: fir_filter_hdl_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fir_filter_hdl_fixpt
          (clk,
           reset,
           clk_enable,
           x,
           ce_out,
           y);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] x;  // sfix16_En15
  output  ce_out;
  output  signed [15:0] y;  // sfix16_En15


  wire enb;
  reg signed [15:0] tmp [0:15];  // sfix16_En15 [16]
  reg signed [15:0] delay_line [0:15];  // sfix16_En15 [16]
  reg signed [15:0] delay_line_1 [0:15];  // sfix16_En15 [16]
  reg signed [39:0] acc;  // sfix40_En30
  reg signed [31:0] delay_line_reg_t_0_0;  // int32
  reg signed [31:0] p5_k;  // int32
  reg signed [15:0] p5_delay_line [0:15];  // sfix16_En15 [16]
  reg signed [31:0] p5_t_0;  // int32
  reg signed [31:0] p5_t_1;  // int32
  reg signed [31:0] p4tmp_t_0;  // int32
  reg signed [31:0] p1_k;  // int32
  reg signed [15:0] p1_t_0 [0:15];  // sfix16_En15 [16]
  reg signed [39:0] p1_acc;  // sfix40_En30
  reg signed [40:0] p1_add_cast [0:15];  // sfix41_En30 [16]
  reg signed [31:0] p1_mul_temp [0:15];  // sfix32_En30 [16]
  reg signed [40:0] p1_add_cast_0 [0:15];  // sfix41_En30 [16]
  reg signed [40:0] p1_add_temp [0:15];  // sfix41_En30 [16]


  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : delay_line_reg_process
      if (reset == 1'b1) begin
        delay_line[0] <= 16'sb0000000000000000;
        delay_line[1] <= 16'sb0000000000000000;
        delay_line[2] <= 16'sb0000000000000000;
        delay_line[3] <= 16'sb0000000000000000;
        delay_line[4] <= 16'sb0000000000000000;
        delay_line[5] <= 16'sb0000000000000000;
        delay_line[6] <= 16'sb0000000000000000;
        delay_line[7] <= 16'sb0000000000000000;
        delay_line[8] <= 16'sb0000000000000000;
        delay_line[9] <= 16'sb0000000000000000;
        delay_line[10] <= 16'sb0000000000000000;
        delay_line[11] <= 16'sb0000000000000000;
        delay_line[12] <= 16'sb0000000000000000;
        delay_line[13] <= 16'sb0000000000000000;
        delay_line[14] <= 16'sb0000000000000000;
        delay_line[15] <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          for(delay_line_reg_t_0_0 = 32'sd0; delay_line_reg_t_0_0 <= 32'sd15; delay_line_reg_t_0_0 = delay_line_reg_t_0_0 + 32'sd1) begin
            delay_line[delay_line_reg_t_0_0] <= tmp[delay_line_reg_t_0_0];
          end
        end
      end
    end

  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //          Generated by MATLAB 24.2 and Fixed-Point Designer 24.2          %
  //                                                                          %
  // %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  // VLSI & FPGA Co-Design
  // Fixed-Point FIR Filter
  // MATLAB R2024b -> HDL Coder -> Verilog
  // FIR Filter:
  // Fs = 1000 Hz
  // Fc = 100 Hz
  // Filter Order = 15
  // Total taps = 16
  // Shift delay line
  always @* begin

    for(p5_t_0 = 32'sd0; p5_t_0 <= 32'sd15; p5_t_0 = p5_t_0 + 32'sd1) begin
      p5_delay_line[p5_t_0] = delay_line[p5_t_0];
    end
    for(p5_k = 32'sd0; p5_k <= 32'sd14; p5_k = p5_k + 32'sd1) begin
      p5_delay_line[32'sd15 - p5_k] = p5_delay_line[32'sd14 - p5_k];
    end
    for(p5_t_1 = 32'sd0; p5_t_1 <= 32'sd15; p5_t_1 = p5_t_1 + 32'sd1) begin
      delay_line_1[p5_t_1] = p5_delay_line[p5_t_1];
    end

  end

  // Current input sample
  always @* begin

    for(p4tmp_t_0 = 32'sd0; p4tmp_t_0 <= 32'sd15; p4tmp_t_0 = p4tmp_t_0 + 32'sd1) begin
      tmp[p4tmp_t_0] = delay_line_1[p4tmp_t_0];
    end

    tmp[0] = x;
  end

  // FIR accumulation
  always @* begin
    p1_t_0[0] = 16'sb1111111111001000;
    p1_t_0[1] = 16'sb1111111110110010;
    p1_t_0[2] = 16'sb0000000000000000;
    p1_t_0[3] = 16'sb0000000101011110;
    p1_t_0[4] = 16'sb0000001110101111;
    p1_t_0[5] = 16'sb0000011001010101;
    p1_t_0[6] = 16'sb0000100000110010;
    p1_t_0[7] = 16'sb0000100011101100;
    p1_t_0[8] = 16'sb0000100000110010;
    p1_t_0[9] = 16'sb0000011001010101;
    p1_t_0[10] = 16'sb0000001110101111;
    p1_t_0[11] = 16'sb0000000101011110;
    p1_t_0[12] = 16'sb0000000000000000;
    p1_t_0[13] = 16'sb1111111110110010;
    p1_t_0[14] = 16'sb1111111111001000;
    p1_t_0[15] = 16'sb0000000000000000;
    p1_acc = 40'sh0000000000;

    for(p1_k = 32'sd0; p1_k <= 32'sd15; p1_k = p1_k + 32'sd1) begin
      p1_add_cast[p1_k] = {p1_acc[39], p1_acc};
      p1_mul_temp[p1_k] = p1_t_0[p1_k] * tmp[p1_k];
      p1_add_cast_0[p1_k] = {{9{p1_mul_temp[p1_k][31]}}, p1_mul_temp[p1_k]};
      p1_add_temp[p1_k] = p1_add_cast[p1_k] + p1_add_cast_0[p1_k];
      if ((p1_add_temp[p1_k][40] == 1'b0) && (p1_add_temp[p1_k][39] != 1'b0)) begin
        p1_acc = 40'sh7FFFFFFFFF;
      end
      else if ((p1_add_temp[p1_k][40] == 1'b1) && (p1_add_temp[p1_k][39] != 1'b1)) begin
        p1_acc = 40'sh8000000000;
      end
      else begin
        p1_acc = p1_add_temp[p1_k][39:0];
      end
    end

    acc = p1_acc;
  end

  // Output
  assign y = (((acc[39] == 1'b0) && (acc[38:30] != 9'b000000000)) || ((acc[39] == 1'b0) && (acc[30:15] == 16'sb0111111111111111)) ? 16'sb0111111111111111 :
              ((acc[39] == 1'b1) && (acc[38:30] != 9'b111111111) ? 16'sb1000000000000000 :
              acc[30:15] + $signed({1'b0, acc[14]})));

  assign ce_out = clk_enable;

endmodule  // fir_filter_hdl_fixpt

